## Summary

- Two main Data Quality Issues detected in initial analysis of users and brands tables are Duplicate Data and Missing Data
- 283 records out of 495 records of users table are duplicate records with only 212 records containing unique information
- 56 out of 495 users state is missing from users table
- 62 out of 495 users last login is missing from users table
- 11 brand name have duplicate data in brands table
- Out of 934 records with brand code 37 are duplicate data in brands table
- 7 records also have duplicate barcode in brands table
- 650 out of 1167 brands category code is missing from brands table
- 612 out of 1167 brands top brand information is missing from brands table
- 234 out of 1167 brandsm brand code information is missing from brands table which is essential for connecting brands table to receipts table

In [1]:
import pandas as pd
import json
import datetime

- users dataframe is created from users.json file

In [2]:
data = []
with open('/Users/mohitkorai/Documents/FetchRewards/users.json') as f:
    for line in f:
        data.append(json.loads(line))
users = pd.DataFrame(data)
users.head()

_id  active               createdDate  \
0  {'$oid': '5ff1e194b6a9d73a3a9f1052'}    True  {'$date': 1609687444800}   
1  {'$oid': '5ff1e194b6a9d73a3a9f1052'}    True  {'$date': 1609687444800}   
2  {'$oid': '5ff1e194b6a9d73a3a9f1052'}    True  {'$date': 1609687444800}   
3  {'$oid': '5ff1e1eacfcf6c399c274ae6'}    True  {'$date': 1609687530554}   
4  {'$oid': '5ff1e194b6a9d73a3a9f1052'}    True  {'$date': 1609687444800}   

                  lastLogin      role signUpSource state  
0  {'$date': 1609687537858}  consumer        Email    WI  
1  {'$date': 1609687537858}  consumer        Email    WI  
2  {'$date': 1609687537858}  consumer        Email    WI  
3  {'$date': 1609687530597}  consumer        Email    WI  
4  {'$date': 1609687537858}  consumer        Email    WI

- Getting Values in JSON columns of _id, createdDate, lastLogin

In [3]:
x = []
for i in users['_id']:
    x.append(*i.values())
users['_id'] = x

In [4]:
x = []
for i in users['createdDate']:
    x.append(*i.values())
users['createdDate'] = x

In [5]:
x = []
for i in users['lastLogin']:
    if pd.notna(i):
        x.append(*i.values())
    else:
        x.append(None)
users['lastLogin'] = x

- Converting 13 digit UNIX timestamp of columns createdDate and lastLogin into datetime format

In [6]:
x = []
for i in users['createdDate']:
    x.append(datetime.datetime.fromtimestamp(int(i)/1000).strftime("%Y-%m-%d %H:%M:%S"))
users['createdDate'] = x

In [7]:
x = []
for i in users['lastLogin']:
    if pd.notna(i):
        x.append(datetime.datetime.fromtimestamp(int(i)/1000).strftime("%Y-%m-%d %H:%M:%S"))
    else:
        x.append(None)
users['lastLogin'] = x

- Chaging column type of createdDate and lastLogin to datetime

In [8]:
users['createdDate'] = pd.to_datetime(users['createdDate'])
users['lastLogin'] = pd.to_datetime(users['lastLogin'])
users.head(10)

_id  active         createdDate           lastLogin  \
0  5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
1  5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
2  5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
3  5ff1e1eacfcf6c399c274ae6    True 2021-01-03 09:25:30 2021-01-03 09:25:30   
4  5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
5  5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
6  5ff1e1e8cfcf6c399c274ad9    True 2021-01-03 09:25:28 2021-01-03 09:25:28   
7  5ff1e1b7cfcf6c399c274a5a    True 2021-01-03 09:24:39 2021-01-03 09:24:39   
8  5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
9  5ff1e1f1cfcf6c399c274b0b    True 2021-01-03 09:25:37 2021-01-03 09:25:37   

       role signUpSource state  
0  consumer        Email    WI  
1  consumer        Email    WI  
2  consumer        Email    WI  
3  consumer        Email    WI  
4  consumer        Email    WI  
5  consumer        Email    WI  
6  consumer        Email    WI  
7  consumer        Email    WI  
8  consumer        Email    WI  
9  consumer        Email    WI

In [9]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   _id           495 non-null    object        
 1   active        495 non-null    bool          
 2   createdDate   495 non-null    datetime64[ns]
 3   lastLogin     433 non-null    datetime64[ns]
 4   role          495 non-null    object        
 5   signUpSource  447 non-null    object        
 6   state         439 non-null    object        
dtypes: bool(1), datetime64[ns](2), object(4)
memory usage: 23.8+ KB


- 56 out of 495 users state is not known
- 62 out of 495 users last login is not known

In [10]:
users['state'].isna().sum()

56

In [11]:
users['lastLogin'].isna().sum()

62

In [12]:
users['_id'].nunique()

212

- 283 records out of 495 records have duplicate data
- 212 records only contain unique id and are unique record

In [13]:
users[users.duplicated()]

_id  active         createdDate           lastLogin  \
1    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
2    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
4    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
5    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
8    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 09:24:04 2021-01-03 09:25:37   
..                        ...     ...                 ...                 ...   
490  54943462e4b07e684157a532    True 2014-12-19 08:21:22 2021-03-05 10:52:23   
491  54943462e4b07e684157a532    True 2014-12-19 08:21:22 2021-03-05 10:52:23   
492  54943462e4b07e684157a532    True 2014-12-19 08:21:22 2021-03-05 10:52:23   
493  54943462e4b07e684157a532    True 2014-12-19 08:21:22 2021-03-05 10:52:23   
494  54943462e4b07e684157a532    True 2014-12-19 08:21:22 2021-03-05 10:52:23   

            role signUpSource state  
1       consumer        Email    WI  
2       consumer        Email    WI  
4       consumer        Email    WI  
5       consumer        Email    WI  
8       consumer        Email    WI  
..           ...          ...   ...  
490  fetch-staff          NaN   NaN  
491  fetch-staff          NaN   NaN  
492  fetch-staff          NaN   NaN  
493  fetch-staff          NaN   NaN  
494  fetch-staff          NaN   NaN  

[283 rows x 7 columns]

- brands dataframe is created from brands.json file

In [14]:
data = []
with open('/Users/mohitkorai/Documents/FetchRewards/brands.json') as f:
    for line in f:
        data.append(json.loads(line))
brands = pd.DataFrame(data)
brands.head()

_id       barcode        category  \
0  {'$oid': '601ac115be37ce2ead437551'}  511111019862          Baking   
1  {'$oid': '601c5460be37ce2ead43755f'}  511111519928       Beverages   
2  {'$oid': '601ac142be37ce2ead43755d'}  511111819905          Baking   
3  {'$oid': '601ac142be37ce2ead43755a'}  511111519874          Baking   
4  {'$oid': '601ac142be37ce2ead43755e'}  511111319917  Candy & Sweets   

       categoryCode                                                cpg  \
0            BAKING  {'$id': {'$oid': '601ac114be37ce2ead437550'}, ...   
1         BEVERAGES  {'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...   
2            BAKING  {'$id': {'$oid': '601ac142be37ce2ead437559'}, ...   
3            BAKING  {'$id': {'$oid': '601ac142be37ce2ead437559'}, ...   
4  CANDY_AND_SWEETS  {'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...   

                        name topBrand                      brandCode  
0  test brand @1612366101024    False                            NaN  
1                  Starbucks    False                      STARBUCKS  
2  test brand @1612366146176    False  TEST BRANDCODE @1612366146176  
3  test brand @1612366146051    False  TEST BRANDCODE @1612366146051  
4  test brand @1612366146827    False  TEST BRANDCODE @1612366146827

- Getting values in JSON column of _id

In [15]:
x = []
for i in brands['_id']:
    x.append(*i.values())
brands['_id'] = x

- Getting ref and id in nested JSON column of cpg

In [16]:
x = []
for i in brands['cpg']:
    x.append(i.get('$ref'))
brands['cpg_ref'] = x

In [17]:
x = []
for i in brands['cpg']:
    x.append(i.get('$id').get('$oid'))
brands['cpg_id'] = x

In [18]:
del brands['cpg']
brands.head(10)

_id       barcode              category  \
0  601ac115be37ce2ead437551  511111019862                Baking   
1  601c5460be37ce2ead43755f  511111519928             Beverages   
2  601ac142be37ce2ead43755d  511111819905                Baking   
3  601ac142be37ce2ead43755a  511111519874                Baking   
4  601ac142be37ce2ead43755e  511111319917        Candy & Sweets   
5  601ac142be37ce2ead43755b  511111719885                Baking   
6  601ac142be37ce2ead43755c  511111219897                Baking   
7  5cdad0f5166eb33eb7ce0faa  511111104810   Condiments & Sauces   
8  5ab15636e4b0be0a89bb0b07  511111504412  Canned Goods & Soups   
9  5c408e8bcd244a1fdb47aee7  511111504788                Baking   

       categoryCode                       name topBrand  \
0            BAKING  test brand @1612366101024    False   
1         BEVERAGES                  Starbucks    False   
2            BAKING  test brand @1612366146176    False   
3            BAKING  test brand @1612366146051    False   
4  CANDY_AND_SWEETS  test brand @1612366146827    False   
5            BAKING  test brand @1612366146091    False   
6            BAKING  test brand @1612366146133    False   
7               NaN                 J.L. Kraft      NaN   
8               NaN      Campbell's Home Style    False   
9               NaN                       test      NaN   

                       brandCode cpg_ref                    cpg_id  
0                            NaN    Cogs  601ac114be37ce2ead437550  
1                      STARBUCKS    Cogs  5332f5fbe4b03c9a25efd0ba  
2  TEST BRANDCODE @1612366146176    Cogs  601ac142be37ce2ead437559  
3  TEST BRANDCODE @1612366146051    Cogs  601ac142be37ce2ead437559  
4  TEST BRANDCODE @1612366146827    Cogs  5332fa12e4b03c9a25efd1e7  
5  TEST BRANDCODE @1612366146091    Cogs  601ac142be37ce2ead437559  
6  TEST BRANDCODE @1612366146133    Cogs  601ac142be37ce2ead437559  
7                     J.L. KRAFT    Cogs  559c2234e4b06aca36af13c6  
8           CAMPBELLS HOME STYLE    Cogs  5a734034e4b0d58f376be874  
9                           TEST    Cogs  59ba6f1ce4b092b29c167346

In [19]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   _id           1167 non-null   object
 1   barcode       1167 non-null   object
 2   category      1012 non-null   object
 3   categoryCode  517 non-null    object
 4   name          1167 non-null   object
 5   topBrand      555 non-null    object
 6   brandCode     933 non-null    object
 7   cpg_ref       1167 non-null   object
 8   cpg_id        1167 non-null   object
dtypes: object(9)
memory usage: 82.2+ KB


- 11 brand name have duplicate data
- Out of 934 records with brand code 37 are duplicate data
- 7 records also have duplicate barcode
- 650 out of 1167 brands do not have category code
- 612 out of 1167 brands do not have top brand information
- 234 out of 1167 brands do not have brand code information which is essential for connecting brands table to receipts table

In [20]:
brands['_id'].nunique()

1167

In [21]:
brands['barcode'].nunique()

1160

In [22]:
brands['name'].nunique()

1156

In [23]:
brands['brandCode'].nunique()

897

In [24]:
brands['categoryCode'].isna().sum()

650

In [25]:
brands['topBrand'].isna().sum()

612

In [26]:
brands['brandCode'].isna().sum()

234